"""
Data models for Consent Guard.

These Pydantic models define the core data structures used throughout
the detection pipeline. Every model is designed around the India CCPA
2023 dark-pattern taxonomy — five categories, no more — and the invariant
that every classification decision must be logged before any
side-effecting action occurs.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class DarkPatternCategory(str, Enum):
    """
    The five India CCPA 2023 dark-pattern categories this system detects.

    Why only five: the PRD explicitly scopes to the CCPA taxonomy.
    Adding categories beyond these would be scope creep with no
    judged benefit in the hackathon context, and would dilute the
    precision/recall reporting.
    """
    FALSE_URGENCY = "false_urgency"
    CONFIRM_SHAMING = "confirm_shaming"
    FORCED_CONTINUITY = "forced_continuity"
    DRIP_PRICING = "drip_pricing"
    BASKET_SNEAKING = "basket_sneaking"
    # Special category for classifier failures — fail-safe, not fail-open.
    CLASSIFIER_ERROR = "classifier_error"


CCPA_CITATIONS = {
    DarkPatternCategory.FALSE_URGENCY: "CCPA Guidelines 2023, Sec 5(1) — Creating false sense of scarcity/urgency",
    DarkPatternCategory.CONFIRM_SHAMING: "CCPA Guidelines 2023, Sec 5(3) — Guilt-tripping consumer into choice",
    DarkPatternCategory.FORCED_CONTINUITY: "CCPA Guidelines 2023, Sec 5(4) — Asymmetric cancellation friction",
    DarkPatternCategory.DRIP_PRICING: "CCPA Guidelines 2023, Sec 5(7) — Concealing mandatory costs until checkout",
    DarkPatternCategory.BASKET_SNEAKING: "CCPA Guidelines 2023, Sec 5(9) — Pre-selecting paid add-ons without consent",
    DarkPatternCategory.CLASSIFIER_ERROR: "System Exception — Automatic Compliance Hold",
}


class Action(str, Enum):
    """Possible actions taken on a message after classification."""
    SENT = "sent"
    HELD = "held"
    APPROVED = "approved"
    REJECTED = "rejected"


class Flag(BaseModel):
    """
    A single dark-pattern flag raised against a message.

    Every flag MUST include a quoted_span from the original message.
    A bare category label without evidence is rejected by the classifier
    pipeline — we never accept a flag we can't point to in the text.
    """
    category: DarkPatternCategory
    confidence: float = Field(ge=0.0, le=1.0)
    quoted_span: str = Field(
        min_length=1,
        description="Exact substring from the original message that triggered this flag. "
                    "Never empty — a flag without evidence is not a flag."
    )
    cleared_by_allowlist: bool = Field(
        default=False,
        description="True only if this was a false_urgency flag cleared by a matching "
                    "real-deadline record. No other category can ever be cleared by the allowlist."
    )
    suggested_rewrite: Optional[str] = Field(
        default=None,
        description="A suggested compliance rewrite generated by the LLM if this flag was triggered."
    )


class Decision(BaseModel):
    """
    A classification decision on a message.

    This is the atomic unit of the audit log. Every decision is written
    to the append-only log BEFORE any side-effecting action (sending,
    holding, or routing to a reviewer). This ordering invariant is the
    foundation of the system's auditability.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    message_id: str
    flags: list[Flag] = Field(default_factory=list)
    action: Action
    reviewer_id: Optional[str] = None
    review_notes: Optional[str] = None


class Message(BaseModel):
    """
    An agent-to-customer message intercepted by Consent Guard.

    This is the input to the detection pipeline. The content field
    holds the raw message text exactly as the agent would have sent it.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    agent_id: str = Field(default="unknown-agent")
    content: str = Field(min_length=1)
    decision: Optional[Decision] = None


class InterceptRequest(BaseModel):
    """Incoming request to intercept and classify an agent message."""
    content: str = Field(min_length=1)
    agent_id: str = Field(default="demo-agent")


class ReviewAction(BaseModel):
    """Request body for approving or rejecting a held message."""
    reviewer_id: str = Field(default="reviewer-1")
    notes: Optional[str] = None
